language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mmgc84/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mmgc84/react-test npm run test

after_successs:
  - docker build -t mmgc84/multi-client ./client
  - docker build -t mmgc84/multi-nginx ./nginx
  - docker build -t mmgc84/multi-server ./server
  - docker build -t mmgc84/multi-worker ./worker
  #Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push mmgc84/multi-client
  - docker push mmgc84/multi-nginx
  - docker push mmgc84/multi-server
  - docker push mmgc84/multi-worker